import Head from 'next/head';
import 'antd/dist/reset.css';
import { XmlTable } from '../components/XmlTable';
import { Header } from '../components/Header';
import { useContext, useEffect } from 'react';
import { UserContext } from '../contexts/UserContext';

import xmlService from '../services/xmlService';

export const getServerSideProps = async () => {
	const xmlConfig = await xmlService.findXmlConfig();

	return {
		props: {
			xmlConfig, // props for the Home component
		},
	};
};

export default function Home({ xmlConfig }) {
	const { xmlData, setXmlData } = useContext(UserContext);

	useEffect(() => {
		if (xmlConfig) {
			setXmlData({
				...xmlData,
				xmlConfig,
			});
		}
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [xmlConfig]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Header />
				<XmlTable />
			</main>
		</>
	);
}
